### ISSUE TITLE
The Takodachi setting seems to not work until I refresh the site

### ISSUE THREAD

**Issue by kvhjdffv** [wotakumoe/wotaku#78]
![2024-10-30 15_11_00-Window](https://github.com/user-attachments/assets/e3b9911d-c3c3-4cf6-8b16-c8940661eb58)
*(Takodachi is not present even though I've enabled the setting)*

![2024-10-30 15_12_35-qBittorrent • Wotaku wiki by Duck - Brave](https://github.com/user-attachments/assets/7c80374e-e99e-4814-a08b-2bc9dd7aeeb8)
*(Takodachi is not gone even though I've disabled the setting)*

**Comment by c032** [comment]
@taskylizard I gave this a try. If you already started writing the fix, feel free to disregard this message. 

Disclaimer: I don't have any experience with this stack, so this is (probably) not the most elegant/idiomatic code.

---

<details>

<summary>diff</summary>

```patch
diff --git a/docs/.vitepress/theme/Layout.vue b/docs/.vitepress/theme/Layout.vue
index d4636b5..bb2c96b 100644
--- a/docs/.vitepress/theme/Layout.vue
+++ b/docs/.vitepress/theme/Layout.vue
@@ -1,5 +1,6 @@
 <script setup lang="ts">
 import DefaultTheme from 'vitepress/theme'
+import { useEventListener, customStorageEventName } from '@vueuse/core'
 import SidebarCard from './components/SidebarCard.vue'
 import AnnouncementPill from './components/AnnouncementPill.vue'
 import NotFoundComponent from './components/NotFound.vue'
@@ -35,7 +36,11 @@ const updateMousePos = (e: MouseEvent | TouchEvent) => {
   }
 }
 
-onMounted(() => {
+const takodachiDisable = ref<(() => void) | null>(null)
+
+const reloadTakodachi = () => {
+  takodachiDisable.value && takodachiDisable.value()
+
   if (prefs.value === 'reduce') return
   const saved = localStorage.getItem('preference-takodachi-enable-disable')
   if (saved === 'Disable') return
@@ -73,12 +78,37 @@ onMounted(() => {
     position.value = { x: finalVec[0], y: finalVec[1] }
   }, 10)
 
-  onUnmounted(() => {
+  takodachiDisable.value = () => {
+    chaser.classList.add('opacity-0')
+
     window.removeEventListener('mousemove', updateMousePos)
     window.removeEventListener('touchstart', updateMousePos)
     clearInterval(intervalId)
-  })
+
+    takodachiDisable.value = null
+  }
+}
+
+onMounted(() => {
+  if (import.meta.env.SSR) return;
+
+  // Storage changed in other documents.
+  useEventListener(window, 'storage', () => {
+    reloadTakodachi()
+  });
+
+  // Storage changed in the same document.
+  useEventListener(window, customStorageEventName, () => {
+    reloadTakodachi()
+  });
+
+  reloadTakodachi()
 })
+
+onUnmounted(() => {
+  takodachiDisable.value && takodachiDisable.value()
+})
+
 const { Layout } = DefaultTheme
 </script>
 
```
</details>

---

I tried to stick to the current code style as much as possible, but I might have missed something.

Explanation:

* Move all the relevant logic from `onMounted` to a `reloadTakodachi` function.
* The `reloadTakodachi` is basically the same as the previous `onMounted`, but instead of hooking to `onUnmounted` at the end, it instead replaces the (new) function `takodachiDisable`.
* All the logic from the original `onUnmounted` was moved to that `takodachiDisable` function. The new `onUnmounted` just calls that function (if set).
* The new `onMounted` now only listens for changes in the localStorage, and calls `reloadTakodachi` when that happens. It also calls `reloadTakodachi` at the end of the function to keep the current behaviour of initializing on mount.
    * [`useEventListener` automatically removes the listener on unmount](https://vueuse.org/core/useEventListener/).
    * [`useLocalStorage` is just a wrapper for `useStorage`](https://github.com/vueuse/vueuse/blob/0f11df11962f5f2e912d66c8544bc6767630780a/packages/core/useLocalStorage/index.ts#L26).
    * [`useStorage` uses these two events](https://github.com/vueuse/vueuse/blob/0f11df11962f5f2e912d66c8544bc6767630780a/packages/core/useStorage/index.ts#L182-L193), and thankfully it's exporting the name of the custom event they're using.
    * The `if (import.meta.env.SSR) return;` line might be unnecessary, but I added it out of an abundance of caution to avoid calling browser-specific code from an SSR environment.

Ideally, I would have liked to use [the preference value](https://github.com/wotakumoe/wotaku/blob/125a20be5c0590fdda670dd8a53dcfba34ad92eb/docs/.vitepress/theme/components/PreferenceRadio.vue#L17) directly, but from a quick look there [doesn't](https://github.com/wotakumoe/wotaku/blob/125a20be5c0590fdda670dd8a53dcfba34ad92eb/docs/.vitepress/configs/shared.ts#L126-L134) [seem](https://vitepress.dev/reference/default-theme-nav#custom-components) to be any easy way to reuse that. So that's why I'm reluctantly listening on localStorage events.

There's at least one problem with this diff tho (but it's too late in my timezone so I'll come back to it tomorrow): When clicking "Enable" and "Disable" quickly the behavior is buggy, and I'm guessing it's related to the `setTimeout`.

I can open a PR if preferred. But in any case, feel free to do whatever with this diff.

**Comment by taskylizard** [comment]
I have not yet written a fix, yeah. The code is definitely messy, I think just refactoring everything into `PreferenceRadio.vue` should be better.
